[webrtc]
#Local IP.
ip = "192.168.1.104"
#Fill in the public IP. If there is no public IP, fill in the local IP.
announcedIp = "192.168.1.104"
webrtcMinPort = 100
webrtcMaxPort = 65535
[signaling_server]
signalingServerPort = 8000
certFile = "server.crt"
keyFile = "server.key"