[webrtc]
#Local IP.
localIp = "127.0.0.1"
#Fill in the public IP. If there is no public IP, fill in the local IP.
announcedIp = "127.0.0.1"
#Port on which webrtc listens.
port = 20000
#This represents the number of worker threads. If it is 0, it is determined by hardware.
workerThreadCount = 0
enableDTX = true
[signaling_server]
#The port on which the signaling service listens.
port = 8000
certFile = "xxx.crt"
keyFile = "xxx.key"
[memory_pool]
#Whether to enable memory pool.
enabled = true
#Maximum length of each memory linked list.
maxListLength = 200
[log]
#Where the log files are stored.
logDirectory = "./logs"
[system]
#Whether to run as a daemon.
runAsdaemon = false
coreDump = true